### PR TITLE
Dependencies & Processes

### PR DESCRIPTION
**Pull request by troglobit**
## Description

 - Fix missing/incomplete dependencies for gencert package
 - Simplify pull-request template
 - Revise Contributing Guidelines
 - Introduce issue templates

[skip ci]

## Checklist

Tick relevant boxes, this PR is-a or has-a:

- [X] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [X] Documentation content changes
- [X] Other (please describe): Processes

### CODE REVIEW

**Comment by jovatn** [comment]
Contributions page looks good to me. Found one typo (ummary => summary)
Sorry for not providing more feedback.

**Comment by troglobit** [comment]
> Contributions page looks good to me. Found one typo (ummary => summary) Sorry for not providing more feedback.

No that's great, thank you!  I've decided to split up this PR in two (because of bugs affecting one of the commits), so the PR template change will be relocated to #449 very soon.

**Review by mattiaswal — APPROVED** [review]
Nice! I really like the bug reporting part!

**Comment by troglobit** [comment]
Offline reviewed also by @wkz and @jovatn with :+1:

**Pull request merged**
