### PR TITLE
confd: Minor Update on YANG Modules Setup Refactor

### PR DESCRIPTION
**Pull request by ahmkar94**
This PR addresses a few points missing in the commit 
# 7d9257

- Fix indentations in a .mk file
- Relocate YANG Modules List Files (.inc)
- Add a missing YANG module to one of the lists

### CODE REVIEW

**Comment by troglobit** [comment]
I still think the setup script should live in `src/confd`, but if the rest of the team wants it in `utils/` it should be named clearly, e.g., `utils/confd-yang-setup.sh`.

Also, files in Infix should use `kebab-case`, not `snake_case`.  The snake_case naming is for functions in C/shell script only.

**Comment by ahmkar94** [comment]
Haven't yet moved the setup.sh from infix/utils to infix/src/confd/scripts.
@troglobit do you think utils is not a good place for it?
It feels a little bit odd to call the script from external builds/projects with the path
---/src/confd/src/script.
I don't have a better argument to keep it in utils dir though xD

**Comment by troglobit** [comment]
> Haven't yet moved the setup.sh from infix/utils to infix/src/confd/scripts. @troglobit do you think utils is not a good place for it? It feels a little bit odd to call the script from external builds/projects with the path ---/src/confd/scripts/. I don't have a better argument to keep it in utils dir though xD

Provided the setup.sh script is truly generic/independent of confd, it can definitely live in `utils/` (I did not realize this independence until today's daily meeting).  Maybe `utils/sysrepo-load-models.sh`?

**Comment by ahmkar94** [comment]
> > Haven't yet moved the setup.sh from infix/utils to infix/src/confd/scripts. @troglobit do you think utils is not a good place for it? It feels a little bit odd to call the script from external builds/projects with the path ---/src/confd/scripts/. I don't have a better argument to keep it in utils dir though xD
> 
> Provided the setup.sh script is truly generic/independent of confd, it can definitely live in `utils/` (I did not realize this independence until today's daily meeting). Maybe `utils/sysrepo-load-models.sh`?

Sounds good! Btw you probably meant: `utils/sysrepo-load-modules.sh` ?

**Comment by troglobit** [comment]
> Sounds good! Btw you probably meant: `utils/sysrepo-load-modules.sh` ?

Had to google; "YANG data models comprise modules and submodules and can define configuration and state data, notifications, and RPCs for use by YANG-based clients. A YANG module defines a data model through its data, and the hierarchical organization of and constraints on that data."

So yeah, you're right of course: `utils/sysrepo-load-modules.sh` :smiley: :+1:

**Review by mattiaswal — APPROVED** [review]
Great work. :100:

**Review by troglobit — APPROVED** [review]

**Pull request merged**
