### PR TITLE
Draft infix deviations for ieee802-ethernet-interfaces

### PR DESCRIPTION
**Pull request by jovatn**
- Add deviations for non-supported statistics
- Limit config, currently we only have ro support
- Add deviations for non-supported configs and status leafs

[skip ci]

### CODE REVIEW

**Comment by jovatn** [comment]
The branch is still in draft state. What is missing are:
- review/discussion: does this deviations file match the current status of ieee802-ethernet-interfaces support (tasks [#86](https://github.com/addiva-elektronik/infix-planning/issues/86) and [#90)](https://github.com/addiva-elektronik/infix-planning/issues/90)
- activation of this yang file, I have forgotten where the script is located, or system for this has changed
- testing it on target: as I am unable to activate it, I have only been able to very it with

**Comment by troglobit** [comment]
Thanks for the PR, please note my comment on addiva-elektronik/infix-planning#86, re: how to include the deviations in confd.

I've assigned @rical as reviewer, he's the one most up-to-date on the current level of support.

**Comment by jovatn** [comment]
I assume my deviations file has conflicts with bootstrapping. Maybe I have removed parts which current factory default relies on?

Even after make distclean and a new rebuild, I get the following output.
```
vatn@vatn-ThinkPad-L13-Gen-3:~/repos/infix-jovatn (jovatn/ieee-ethernet-deviations)$ make run
make[1]: Entering directory '/home/vatn/repos/infix-jovatn/buildroot'
Starting Qemu  ::  Ctrl-a x -- exit | Ctrl-a c -- toggle console/monitor
● ● ●  Infix — a Network Operating System latest-629-g34dfb98-dirty ══════
[ OK ] Mounting filesystems from /etc/fstab
[ OK ] Restoring system clock (UTC) from RTC
[ OK ] Bootstrapping random seed
[ OK ] Seeding random number generator
[ OK ] Verifying D-Bus machine UUID
[ OK ] Starting Device event daemon (udev)
[ OK ] Requesting device events
[ OK ] Requesting subsystem events
[ OK ] Waiting for udev to finish
[ OK ] Starting System log daemon
[ OK ] Probing system information
[ OK ] Probing network interfaces
[ OK ] Starting D-Bus message bus daemon
[FAIL] Bootstrapping YANG datastore
Nov 22 2023 09:46:57 root[2304]: The device has reached an unrecoverable error, please RMA.
[WARN] Timeout waiting for error:1 to run, resuming bootstrap

Please press Enter to activate this console.
```

**Comment by jovatn** [comment]
I will try by removing most deviations. If that works, I will add them one-by-one ...

**Comment by troglobit** [comment]
You can debug your new YANG models like this:

```diff
diff --git a/package/confd/confd.conf b/package/confd/confd.conf
index 0489488..d795b56 100644
--- a/package/confd/confd.conf
+++ b/package/confd/confd.conf
@@ -1,6 +1,6 @@
 #set DEBUG=1
 
-run name:bootstrap log:prio:user.notice norestart <pid/syslogd> \
+run name:bootstrap log:console norestart <pid/syslogd> \
        [S] /usr/libexec/confd/bootstrap \
        -- Bootstrapping YANG datastore
 
diff --git a/src/confd/bin/bootstrap b/src/confd/bin/bootstrap
index 7fde631..6ebe96e 100755
--- a/src/confd/bin/bootstrap
+++ b/src/confd/bin/bootstrap
@@ -180,6 +180,7 @@ sysrepoctl -s $SEARCH                                                       \
           -i infix-system@2023-10-19.yang      -g wheel -p 0660        \
           -i infix-services@2023-10-16.yang    -g wheel -p 0660        \
           -i ieee802-ethernet-interface@2019-06-21.yang -g wheel -p 0660 \
+          -i infix-routing@2013-10-27.yang     -g wheel -p 0660        \
           -I "${INIT_DATA}"
 rc=$?
 
```

**Comment by troglobit** [comment]
This is what I get:

```
[ ⋯  ] Bootstrapping YANG datastore[ERR] Duplicate instance of "module". (Data location "/sysrepo:sysrepo-modules/module[name='infix-routing']".)
sysrepoctl error: Failed to install modules (libyang error)
For more details you may try to increase the verbosity up to "-v3".
[FAIL] 
Nov 22 2023 09:55:55 root[2299]: The device has reached an unrecoverable error, please RMA.
```

**Comment by troglobit** [comment]
This is what I get:

```
[ ⋯  ] Bootstrapping YANG datastore[ERR] Invalid deviation replacing "config" property "config false" which is not present. (Path "/infix-ethernet-interface:{deviation='/if:interfaces/if:interface/eth:ethernet'}".)
sysrepoctl error: Failed to install modules (libyang error)
For more details you may try to increase the verbosity up to "-v3".
[FAIL] 
Nov 22 2023 09:59:42 root[2299]: The device has reached an unrecoverable error, please RMA.
```

**Comment by jovatn** [comment]
Right, I should learn to use yanglint!
The culprit is the following part. I will adapt and try again ...
```
  deviation "/if:interfaces/if:interface/eth:ethernet" {
    deviate replace {
      config false;
    }
  }

```

**Comment by troglobit** [comment]
Try this:

```yang
  deviation "/if:interfaces/if:interface/eth:ethernet" {
    deviate add {
      config false;
    }
  }
```

**Comment by jovatn** [comment]
Right. Found it in parallel. Thx anyway!

**Review by troglobit — APPROVED** [review]
Tests pass, this looks great!

**Pull request merged**
