### PR TITLE
Misc fixes

### LINKED ISSUE #635: ospf: all router neighbors reported as neighbor on every interface
### Current Behavior

Tested on Infix 24.06.0 in GNS3, but bug ought to exist in 24.08.0 as well.

By reading out interface neighbors from ietf-ospf.yang, you should be able to list neighbor(s) per interface
```
    container neighbors {
      config false;
      description
        "All neighbors for the interface.";
      list neighbor {
        key "neighbor-router-id";
        description
          "List of interface OSPF neighbors.";
        leaf neighbor-router-id {
          type rt-types:router-id;
          description
            "Neighbor's Router ID.";
        }
        uses neighbor-state;
      }
    }
```
However, infix lists *all* neighbors of the device as neighbors on every interface (even the loopback).

Look at router "r6" in the picture below.
Screenshot from 2024-09-16 09-13-00

On its interface "eth0" it should list r4 as neighbor, which happens to have router-id 10.1.1.4, but it lists r3 (10.1.1.3) and r5 (10.1.1.5) as well. And it does so on every OSPF interface (eth0, eth1, eth2 and lo).

```
admin@R6:~$ sysrepocfg -X -d operational -fjson -x "/ietf-routing:routing/ietf-routing:control-plane-protocols"
{
  "ietf-routing:routing": {
    "control-plane-protocols": {
      "control-plane-protocol": [
        {
          "type": "ietf-ospf:ospfv2",
          "name": "default",
          "ietf-ospf:ospf": {
            "address-family": "ipv4",
            "router-id": "10.1.1.6",
...
            "areas": {
              "area": [
                {
                  "area-id": "0.0.0.0",
                  "area-type": "normal-area",
                  "interfaces": {
                    "interface": [
                      {
                        "name": "eth0",
                        "interface-type": "point-to-point",
                        "passive": false,
                        "enabled": true,
                        "state": "point-to-point",
                        "neighbors": {
                          "neighbor": [
                            {
                              "neighbor-router-id": "10.1.1.4",
                              "address": "10.1.1.4",
                              "dr-router-id": "0.0.0.0",
                              "bdr-router-id": "0.0.0.0",
                              "state": "full",
                              "dead-timer": 35695
                            },
                            {
                              "neighbor-router-id": "10.1.1.3",
                              "address": "10.1.1.3",
                              "dr-router-id": "0.0.0.0",
                              "bdr-router-id": "0.0.0.0",
                              "state": "full",
                              "dead-timer": 35138
                            },
                            {
                              "neighbor-router-id": "10.1.1.5",
                              "address": "10.1.1.5",
                              "dr-router-id": "0.0.0.0",
                              "bdr-router-id": "0.0.0.0",
                              "state": "full",
                              "dead-timer": 36525
                            }
                          ]
                        }
                      },
                      {
                        "name": "eth1",
                        "interface-type": "point-to-point",
  ...
```
Compare this with CLI status output
```
admin@R6:/> show ospf neighbor 

Neighbor ID     Pri State           Up Time         Dead Time Address         Interface                        RXmtL RqstL DBsmL
10.1.1.4          1 Full/-          42m49s            30.010s 10.1.1.4        eth0:10.1.1.6                        0     0     0
10.1.1.3          1 Full/-          42m50s            39.453s 10.1.1.3        eth1:10.1.1.6                        0     0     0
10.1.1.5          1 Full/-          42m49s            30.840s 10.1.1.5        eth2:10.1.1.6                        0     0     0

admin@R6:/> 
```

### Expected Behavior

```
admin@R6:~$ sysrepocfg -X -d operational -fjson -x "/ietf-routing:routing/ietf-routing:control-plane-protocols"
{
  "ietf-routing:routing": {
    "control-plane-protocols": {
      "control-plane-protocol": [
        {
          "type": "ietf-ospf:ospfv2",
          "name": "default",
          "ietf-ospf:ospf": {
            "address-family": "ipv4",
            "router-id": "10.1.1.6",
...
            "areas": {
              "area": [
                {
                  "area-id": "0.0.0.0",
                  "area-type": "normal-area",
                  "interfaces": {
                    "interface": [
                      {
                        "name": "eth0",
                        "interface-type": "point-to-point",
                        "passive": false,
                        "enabled": true,
                        "state": "point-to-point",
                        "neighbors": {
                          "neighbor": [
                            {
                              "neighbor-router-id": "10.1.1.4",
                              "address": "10.1.1.4",
                              "dr-router-id": "0.0.0.0",
                              "bdr-router-id": "0.0.0.0",
                              "state": "full",
                              "dead-timer": 35695
                          }
                          ]
                        }
                      },
                      {
                        "name": "eth1",
                        "interface-type": "point-to-point",
  ...
```

### Steps To Reproduce

1. Setup Infix 24.06.0 on (at least) three devices in GNS3 and connect them (R1 <=> R2 <=> R3)
2. Setup OSPF, preferably by point-to-point links
3. Check in CLI that they get ospf connectivity ('show ospf neighbor') on R2, and verify that R2 has a neighbor on two different interfaces.
4. Use sysrepocfg to extract yang-model of operational state on R2, `sysrepocfg -X -d operational -fjson -x "/ietf-routing:routing/ietf-routing:control-plane-protocols`
5. You should see that " lists R1 and R3 as neighbors on both sides.

### LINKED ISSUE #648: Bump kernel to 6.6.52 for CN9130 NIC fixes, and more
An extract from the ChangeLog.  Worth noting, [Marvell Octeon][TX2] mentioned below is the CN913x SoC family.

```
...
 drivers/net/ethernet/marvell/octeontx2/af/rvu.h                |    3 
 drivers/net/ethernet/marvell/octeontx2/af/rvu_nix.c            |   59 +++++-
      octeontx2-af: Modify SMQ flush sequence to drop packets
 drivers/nvmem/core.c                                           |   13 +
      nvmem: core: add nvmem_dev_size() helper
 drivers/nvmem/u-boot-env.c                                     |   91 +++++-----
      nvmem: u-boot-env: error if NVMEM device is too small
      nvmem: u-boot-env: use nvmem_add_one_cell() nvmem subsystem helper
      nvmem: u-boot-env: use nvmem device helpers
 net/netfilter/nft_socket.c                                     |    7 
      netfilter: nft_socket: fix sk refcount leaks
...
```

For a summary of changes, see <https://lwn.net/Articles/990767/>

[TX2]: https://www.marvell.com/content/dam/marvell/en/public-collateral/embedded-processors/marvell-infrastructure-processors-octeon-tx2-cn913x-product-brief.pdf

### PR DESCRIPTION
**Pull request by mattiaswal**
## Description

- Fix #648 
- Fix #635 
- Fix ietf-interface parts of #606  (except vlan_qos)

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [x] Bugfix
  - [x] Regression tests
  - [x] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by troglobit** [comment]
I see your branch also fails on alder@monza, for OSPF unnumbered and services basic.  The latter test is likely the VLAN splitter eating LLDP frames, but the OSPF test sometimes passes when run again on HW, so maybe flaky?  We can have a chat with @wkz today on how to proceed with these two.

**Review by troglobit — APPROVED** [review]
Great work on this, in a very short timeframe!  No notes :smiley:

**Comment by jovatn** [comment]
Verified by gns3 that #635 is solved. Only the correct neighbor is shown per interface, when tested with unnumbered OSPF interfaces.

**Comment by jovatn** [comment]
I also tried with a (regular) OSPF broadcast interface, and it showed expected results too!

In output below, the following interfaces are of interest
- lo (loopback): no neighbors!
- eth0 and eth1 (point-to-point unnumbered interfaces): a single neighbor
- eth2 (broadcast interface): more than one neighbor (here only two more were attached)

```
admin@infix-84-ff-ff:~$ sysrepocfg -X -d operational -fjson -x "/ietf-routing:routing/ietf-routing:control-plane-protocols"
....
           "areas": {
              "area": [
                {
                  "area-id": "0.0.0.0",
                  "area-type": "normal-area",
                  "interfaces": {
                    "interface": [
                      {
                        "name": "eth0",
                        "interface-type": "point-to-point",
                        "passive": false,
                        "enabled": true,
                        "state": "point-to-point",
                        "neighbors": {
                          "neighbor": [
                            {
                              "neighbor-router-id": "10.0.1.2",
                              "address": "10.0.1.2",
                              "dr-router-id": "0.0.0.0",
                              "bdr-router-id": "0.0.0.0",
                              "state": "full",
                              "dead-timer": 32987
                            }
                          ]
                        }
                      },
                      {
                        "name": "eth1",
                        "interface-type": "point-to-point",
                        "passive": false,
                        "enabled": true,
                        "state": "point-to-point",
                        "neighbors": {
                          "neighbor": [
                            {
                              "neighbor-router-id": "10.0.1.5",
                              "address": "10.0.1.5",
                              "dr-router-id": "0.0.0.0",
                              "bdr-router-id": "0.0.0.0",
                              "state": "full",
                              "dead-timer": 39464
                            }
                          ]
                        }
                      },
                      {
                        "name": "eth2",
                        "interface-type": "broadcast",
                        "passive": false,
                        "enabled": true,
                        "state": "dr-other",
                        "dr-router-id": "10.10.0.2",
                        "dr-ip-addr": "10.10.0.2",
                        "bdr-router-id": "10.10.0.1",
                        "bdr-ip-addr": "10.10.0.1",
                        "neighbors": {
                          "neighbor": [
                            {
                              "neighbor-router-id": "10.10.0.1",
                              "address": "10.10.0.1",
                              "dr-router-id": "10.10.0.2",
                              "bdr-router-id": "10.10.0.1",
                              "state": "full",
                              "dead-timer": 38931
                            },
                            {
                              "neighbor-router-id": "10.10.0.2",
                              "address": "10.10.0.2",
                              "dr-router-id": "10.10.0.2",
                              "bdr-router-id": "10.10.0.1",
                              "state": "full",
                              "dead-timer": 38989
                            }
                          ]
                        }
                      },
                      {
                        "name": "lo",
                        "passive": false,
                        "enabled": true,
                        "state": "loopback"
                      }
                    ]
                  }
                }
....
```

**Pull request merged**
