### PR TITLE
test/qeneth: Update submodule

### PR DESCRIPTION
**Pull request by ahmkar94**
Update Qeneth submodule to reference the recent changes that resolve the gvpr warnings previously appearing in the test environment.

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [x] Bugfix
  - [x] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Review by troglobit — CHANGES_REQUESTED** [review]
The commit message needs a final line to close the matching issue.

"Fixes #660"

**Comment by troglobit** [comment]
Perfect, thanks!  I'll approve and let you merge right after the v24.09 tag has been placed (sometime after lunch :)

**Comment by ahmkar94** [comment]
> Perfect, thanks! I'll approve and let you merge right after the v24.09 tag has been placed (sometime after lunch :)

Sounds good :)

**Review by troglobit — APPROVED** [review]
Approved for v24.10.  Please update branch before merging -- there's button in the Web interface for this.  I suggest selecting *Update with Rebase*.

**Pull request merged**
