### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by troglobit**
## Description

 - Bump curiOS httpd sample container, latest Buildroot + better BusyBox config/tools
 - Fix blocking delete of containers in sysrepo callback, run in background
 - Fix column width for "show bridge mdb"
 - klish: improved error/warning message for unknown/incomplete command

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [X] Bugfix
  - [ ] Regression tests
  - [x] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by troglobit** [comment]
I'll add ChangeLog in the morning.

**Comment by troglobit** [comment]
There, unit test and ChangeLog updated.  Ready for review @wkz + @mattiaswal

**Comment by troglobit** [comment]
Not sure why the container tests fail, probably has to do with the curiOS upgrade, at least I've managed to reproduce it here now.  Looking into it ...

**Comment by troglobit** [comment]
Had obviously forgot to update a hard-coded string.  Fixed.

**Review by wkz — APPROVED** [review]
:ship:!

**Review by mattiaswal — APPROVED** [review]
:100:

**Comment by troglobit** [comment]
Changes after approval due to conflicts with #480, only minor fixups force-pushed.

Tests still pass so merging.

**Pull request merged**
