### PR TITLE
Update buildroot to 2024.02.9

### PR DESCRIPTION
**Pull request by mattiaswal**
## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [ ] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Test changes
  - [ ] Checked in changed Readme.adoc (make test-spec)
  - [ ] Added new test to group Readme.adoc and yaml file
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
  - [ ] ChangeLog updated (for major changes)
- [ ] Other (please describe):

### CODE REVIEW

**Comment by troglobit** [comment]
(I guess you'll squash these two commits later, right?)

**Comment by mattiaswal** [comment]
> (I guess you'll squash these two commits later, right?)



> (I guess you'll squash these two commits later, right?)

Ofc, this is just for testing right now.

**Review by troglobit — APPROVED** [review]
Just added the `ci:main` tag to ensure the container tests get some exercise as well on this branch.  As soon as the tests pass we can merge, I have no comments.

I guess there were no conflicts merging in the latest buildroot?

**Comment by mattiaswal** [comment]
> Just added the `ci:main` tag to ensure the container tests get some exercise as well on this branch. As soon as the tests pass we can merge, I have no comments.
> 
> I guess there were no conflicts merging in the latest buildroot?

only FRR, they updated to a security update for 8.5 branch, we use 9.1

**Pull request merged**
