### PR TITLE
test: add top level unit test suite

### PR DESCRIPTION
**Pull request by rical**
This currently includes cli-pretty tests. It could be executed separately to clarify test results in github actions. This commit includes it in the main test execution. The most important thing is that it's executed.

### CODE REVIEW

**Comment by troglobit** [comment]
It fails because of "file not found" for missing `test/case/pretty_cli/run.sh` but that seems to be there, so my guess is that this fails because Reggie Regression (github job) still uses the minimal defconfig.

If you include a fix to #127 in your PR I suspect this will fix the problem.

**Comment by rical** [comment]
> It fails because of "file not found" for missing `test/case/pretty_cli/run.sh` but that seems to be there, so my guess is that this fails because Reggie Regression (github job) still uses the minimal defconfig.
> 
> If you include a fix to #127 in your PR I suspect this will fix the problem.

Thanks for investigating. I pushed a new version that **won't** fix the problem but includes some new 9pm commits for more graceful error checking of missing files. Lets see if we at least can make the error look better ;)

**Comment by troglobit** [comment]
This still fails with:

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/9pm_e_2h98lp/9pm_iusksjh5_db'
make[1]: *** [/home/runner/work/infix/infix/board/x86_64/board.mk:15: test-qeneth] Error 1
```

Do we have any idea why?

**Comment by rical** [comment]
> This still fails with:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/9pm_e_2h98lp/9pm_iusksjh5_db'
> make[1]: *** [/home/runner/work/infix/infix/board/x86_64/board.mk:15: test-qeneth] Error 1
> ```
> 
> Do we have any idea why?

Apparently there's no bash interpreter? I changed the script `run.sh` to call `#!/usr/bin/env bash` which revealed the real problem: `env: can't execute 'bash': No such file or directory`. I tried adding it in `regression.yml` as `shell: bash`, but no luck.

**Comment by troglobit** [comment]
> > This still fails with:
> > ```
> > FileNotFoundError: [Errno 2] No such file or directory: '/tmp/9pm_e_2h98lp/9pm_iusksjh5_db'
> > make[1]: *** [/home/runner/work/infix/infix/board/x86_64/board.mk:15: test-qeneth] Error 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do we have any idea why?
> 
> Apparently there's no bash interpreter? I changed the script `run.sh` to call `#!/usr/bin/env bash` which revealed the real problem: `env: can't execute 'bash': No such file or directory`. I tried adding it in `regression.yml` as `shell: bash`, but no luck.

Very odd, even the minimal defconfig has bash ... or wait, is this for executing inside the Alpine Docker?  If so, I don't think we have bash there, only 'ash' the default BusyBox shell included in the basic Alpine install.

**Comment by troglobit** [comment]
There we go, all PASS! :-)

**Review by troglobit — APPROVED** [review]

**Pull request merged**
