### PR TITLE
Add support for `ip addr show proto name` & devguide update

### PR DESCRIPTION
**Pull request by troglobit**
## Description

While working on a customer feature I realized it was not possible to do `ip addr show profinet`.  Turns out that even though a lot has happened with iproute2 v6.7.0, this tiny little thing is still not supported.

Also, while reviewing documentation I cleaned up some grammar and simplified parts of the Devloper's Guide.

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [ ] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [X] Documentation content changes
- [X] Other (please describe): non-visible user change

### CODE REVIEW

**Review by mattiaswal — CHANGES_REQUESTED** [review]
Can not this be in rt_protos.d?

**Review by wkz — APPROVED** [review]
Squeaky clean! :100:

**Comment by troglobit** [comment]
> Can not this be in rt_protos.d?

Unfortunately not, that's only for routes.  See here:

https://github.com/kernelkit/iproute2/blob/226a8b532fc074165ba76d71c4488629daed2625/lib/rt_names.c#L304-L318

**Comment by mattiaswal** [comment]
> > Can not this be in rt_protos.d?
> 
> Unfortunately not, that's only for routes. See here:
> 
> https://github.com/kernelkit/iproute2/blob/226a8b532fc074165ba76d71c4488629daed2625/lib/rt_names.c#L304-L318

Crap, I wondered yesterday if it was supported there.

**Review by mattiaswal — APPROVED** [review]

**Pull request merged**
