### PR TITLE
Container firewall test

### PR DESCRIPTION
**Pull request by troglobit**
## Description

 - Minor cleanups
 - #598 
 - Proposal for how a test section/group could look

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [ ] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [X] Test changes
  - [X] Checked in changed Readme.adoc (make test-spec)
  - [X] Added new test to group Readme.adoc and yaml file
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
  - [ ] ChangeLog updated (for major changes)
- [ ] Other (please describe):

### CODE REVIEW

**Comment by troglobit** [comment]
Ping @jovatn, this PR also contains a proposal for how a test section/group could look.  It's a litmus test to see if we're aligned or if we need to discuss this a bit more.  (Re: discussion you, me, and @axkar had the other day.)

**Comment by jovatn** [comment]
Great work!
Two comments:
- On section/group: Although informative to have a description on each section, I realized there are some risks. (1) Easy to forget to update if tests are added, removed or modified. (2) What if we create a test-suite which excludes some of the tests within a section. Then the section description risk being incorrect. **This said**, I still think it is a good idea, but we ought to _avoid being too specific_ in the section description.
- On the firewall container test: Great! I only have a question on formatting; should we rename ext0/int0 to ext1/int1 or ext/int? No big deal, but we have changed the port naming to start by 1 instead of 0 in all(?) other tests.

**Comment by troglobit** [comment]
>     * On section/group: Although informative to have a description on each section, I realized there are some risks. (1) Easy to forget to update if tests are added, removed or modified. (2) What if we create a test-suite which excludes some of the tests within a section? Then the section description risks being incorrect. **This said**, I still think it is a good idea, but we ought to _avoid being too specific_ in the section description.

OK, I can drop it until we've agreed upon a strategy for these.  Would that be better?  (ping @mattiaswal)

>     * On the firewall container test: Great! I only have a question on formatting; should we rename ext0/int0 to ext1/int1 or ext/int? No big deal, but we have changed the port naming to start by 1 instead of 0 in all(?) other tests.

Well, we have cases where we use `veth0a<-->veth0b` in examples and documentation, so I don't think this would be much of a difference.

**Comment by jovatn** [comment]
> Well, we have cases where we use `veth0a<-->veth0b` in examples and documentation, so I don't think this would be much of a difference.

I agree. We frequently use br0 as well.

**Comment by troglobit** [comment]
> > Well, we have cases where we use `veth0a<-->veth0b` in examples and documentation, so I don't think this would be much of a difference.
> I agree. We frequently use br0 as well.

Yeah, I think we talked about this at one point AFK as well.  Iirc, the agreement was to use *positive integers* for physical interfaces (or interfaces supposed to emulate physical interfaces in virtual setups like Qemu/GNS3).

Side note, I wonder if the confusion in computer science, and computers in general, stems from the one in [*natural numbers*](https://en.wikipedia.org/wiki/Natural_number), which some define as [excluding zero](https://www.cuemath.com/numbers/natural-numbers/)?

**Comment by mattiaswal** [comment]
> Great work! Two comments:
> 
> * On section/group: Although informative to have a description on each section, I realized there are some risks. (1) Easy to forget to update if tests are added, removed or modified. (2) What if we create a test-suite which excludes some of the tests within a section? Then the section description risks being incorrect. **This said**, I still think it is a good idea, but we ought to _avoid being too specific_ in the section description.
> * On the firewall container test: Great! I only have a question on formatting; should we rename ext0/int0 to ext1/int1 or ext/int? No big deal, but we have changed the port naming to start by 1 instead of 0 in all(?) other tests.

I agree on the group part, but as I see this is better than nothing. The test specification will not be done with this release, we must continue to work with the graphical parts.

My idea of the group page is to describe the functions tested overall, but I doubt someone has time to do it now.

**Review by mattiaswal — APPROVED** [review]
Great work! Gold star for you! :star: :star: :star: :star: :star:

**Pull request merged**
